### ISSUE TITLE
[Course Management System]: Enhancement: Implement Admin Access to Wait List Feature

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes/rsschool-app#2431]
## Description

Currently, administrators encounter a backend error (403 Forbidden status code) when accessing the wait list feature, restricting their ability to manage this critical system component effectively. The error message received is:

```json
{
    "message": "Forbidden resource",
    "error": "Forbidden",
    "statusCode": 403
}
```

This issue necessitates a fix in the access control logic, specifically at [this line in the interviews.controller.ts file](https://github.com/rolling-scopes/rsschool-app/blob/master/nestjs/src/courses/interviews/interviews.controller.ts#L88), where Role.Admin needs to be added.

## Objectives

- **Error Resolution**: Resolve the access control issue for admin users.
- **Access Control Update**: Ensure admins have the necessary permissions to access the wait list.

## Tasks

1. **Backend Access Control Fix**:
   - [ ] Add `Role.Admin` to the access control logic in the specified part of the codebase.

2. **Access Control Verification**:
   - [ ] Review and update access control policies to confirm admin access is appropriately set.
   - [ ] Test admin access to the wait list feature under various scenarios.

3. **Quality Assurance**:
   - [ ] Perform thorough testing to ensure the issue is resolved.
   - [ ] Check that other roles and system functionalities remain unaffected.

## Expected Outcome

Following the implementation of these changes, administrators should gain proper access to the wait list feature, enhancing system usability and administrative efficiency.
