### ISSUE TITLE
[Course Management System]: Enhance Data Model with `certificateThreshold` Field and Add Tooltip in Form

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes/rsschool-app#2441]
## Description

We need to add a new field `certificateThreshold` to the Course data model. This field will store the minimum score percentage required for students to achieve in order to receive a certificate, with a default value of 70%. Additionally, in the course creation and editing forms, an input field for `certificateThreshold` should be added. This field should be accompanied by an information icon, displaying a tooltip that explains the purpose and use of the `certificateThreshold`. The permissible range for input should be between 1% and 100%.

## Objectives

- **Data Model Enhancement**: Add `certificateThreshold` field to the Course model.
- **Form UI Update**: Integrate an input field for `certificateThreshold` in course creation and editing forms, with a tooltip for guidance.

## Tasks

1. **Data Model Update**:
   - [ ] Add `certificateThreshold` field to Course model in the database.
   - [ ] Set the default value of `certificateThreshold` to 70%.

2. **Form Update for Course Creation and Editing**:
   - [ ] Add an input field for `certificateThreshold` on the course creation and editing forms.
   - [ ] Implement a tooltip for the `certificateThreshold` input field.
     - Example Code:
       ```html
       <Form.Item
         name="certificateThreshold"
         label="Certificate Threshold"
         initialValue={70}
         tooltip="Minimum score percentage required for students to qualify for a certificate."
         rules={[{ required: true, message: 'Please input the certificate threshold!', whitespace: true }]}
       >
         <Input />
       </Form.Item>
       ```
   - [ ] Ensure the input range for `certificateThreshold` is between 1% and 100%.

3. **Validation and Testing**:
   - [ ] Validate that the `certificateThreshold` field correctly stores and retrieves data.
   - [ ] Test the input field and tooltip on both creation and editing forms for functionality and clarity.

## Expected Outcome

The addition of the `certificateThreshold` field and its corresponding input field with a tooltip in the course creation and editing forms will enhance the course management system's functionality. It provides a clear and customizable benchmark for student certification and aids in user understanding through the tooltip.
